### PR TITLE
bulls and cows history GUI

### PR DESCRIPTION
**Pull request by yuritaba**
@sjp-codes this addresses the issue #19 

This PR updates the Bulls and Cows game. Now, the user can see their last attempts.
How it was:

Captura de Tela 2024-10-21 às 16 33 23

How it is now:

Captura de Tela 2024-10-21 às 17 22 21

Also, changed the position of the give up button because it was behind the text label.

### CODE REVIEW

**Comment by yuritaba** [comment]
Hi @sjp-codes! Could you please review this pull request? Thank you in advance

**Comment by sxijyoti** [comment]
I think you forgot to change the fifthscreen back to startscreen....i will merge it once that's sorted

**Comment by yuritaba** [comment]
Oh, that is true. I am changing it right now!

**Comment by yuritaba** [comment]
@sjp-codes now I think it should be good. Thank you for the feedback!

**Pull request merged**
